In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
cd /content/drive/MyDrive/GitHub/Website-Fingerprinting/Random-Forest

/content/drive/MyDrive/GitHub/Website-Fingerprinting/Random-Forest


In [4]:
pwd

'/content/drive/MyDrive/GitHub/Website-Fingerprinting/Random-Forest'

In [5]:
import pickle
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from scipy.spatial.distance import pdist, squareform



with open('mon2.pkl', 'rb') as file:
    df2 = pickle.load(file)

#whole data
X = df2[['total_income', 'total_outcome', 'packet_num', 'outgoing_ratio', 'incoming_ratio', 'duration','duration_per_packet','time_mean','time_std','time_var', 'size_mean', 'size_std','size_var','cumlative_mean','cumlative_var','burst_mean','burst_std','burst_var']]
y = df2['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

rf_model = RandomForestClassifier(max_depth=20, n_estimators=100,random_state=42, class_weight='balanced')
rf_model.fit(X_train, y_train)

predictions = rf_model.predict(X_test)


In [6]:
#metrics
from sklearn.metrics import precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, predictions)
precision = precision_score(y_test, predictions, average='weighted')
recall = recall_score(y_test, predictions, average='weighted')
f1 = f1_score(y_test, predictions, average='weighted')

print("<closed_multi>")
print(f'정확도: {accuracy:.2f}')
print(f'정밀도: {precision:.2f}')
print(f'재현율: {recall:.2f}')
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, predictions)
print(cm)

<closed_multi>
정확도: 0.71
정밀도: 0.71
재현율: 0.71
[[34  0  0 ...  0  0  1]
 [ 0 23  0 ...  0  0  0]
 [ 0  0 45 ...  0  1  0]
 ...
 [ 0  0  1 ... 29  0  0]
 [ 0  0  0 ...  0 42  0]
 [ 2  0  0 ...  2  1 32]]
