<a href="https://colab.research.google.com/github/geeoneee/Website-Fingerprinting/blob/gradient_boosting/Gradient_Boosting_unmon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prerequisite



In [47]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


##이진분류

In [48]:
import pickle
with open("/content/drive/MyDrive/GitHub/global/mon2.pkl", 'rb') as fi: # Path to mon_standard.pkl in Colab
    df1 = pickle.load(fi)
print("Loading mon_df1_contiuous...")

import pickle
with open("/content/drive/MyDrive/GitHub/global/unmon2.pkl", 'rb') as fi: # Path to mon_standard.pkl in Colab
    df2 = pickle.load(fi)
print("Loading mon_df2_contiuous...")

Loading mon_df1_contiuous...
Loading mon_df2_contiuous...


In [49]:
df1['label'] = 1
df1.head()

label  packet_num  total_income  total_outcome  outgoing_ratio  \
0      1        1421           121           1300        0.914849   
1      1         518            80            438        0.845560   
2      1        1358           118           1240        0.913108   
3      1        1446           122           1324        0.915629   
4      1        1406           115           1291        0.918208   

   incoming_ratio  duration  duration_per_packet  time_mean  time_std  \
0        0.085151     10.14             0.007136   4.315749  1.128342   
1        0.154440     10.16             0.019614   4.611815  1.370610   
2        0.086892     11.11             0.008181   5.488969  1.179265   
3        0.084371     13.36             0.009239   5.995512  1.708888   
4        0.081792     10.64             0.007568   4.698869  1.297085   

   time_var  size_mean  size_std  size_var  cumlative_std  cumlative_mean  \
0  1.273156   4.315749  1.128342  1.273156  185143.121578  -307557.787474   
1  1.878571   4.611815  1.370610  1.878571   52114.349528   -86710.857143   
2  1.390665   5.488969  1.179265  1.390665  175190.919799  -297018.438881   
3  2.920298   5.995512  1.708888  2.920298  188050.453003  -316360.409405   
4  1.682428   4.698869  1.297085  1.682428  183907.494477  -308565.940256   

   cumlative_var    burst_std   burst_mean     burst_var  
0   3.427798e+10  7804.680303 -3901.109677  6.091303e+07  
1   2.715905e+09  5268.809112 -1981.935484  2.776035e+07  
2   3.069186e+10  7571.208934 -3811.178808  5.732320e+07  
3   3.536297e+10  7796.126033 -3873.811321  6.077958e+07  
4   3.382197e+10  7396.058816 -3838.369427  5.470169e+07

In [50]:
df2.head()

label  packet_num  total_income  total_outcome  outgoing_ratio  \
0     -1         130            29            101        0.776923   
1     -1        9927           738           9189        0.925657   
2     -1         359            74            285        0.793872   
3     -1        9948           541           9407        0.945617   
4     -1        2508           293           2215        0.883174   

   incoming_ratio  duration  duration_per_packet  time_mean  time_std  \
0        0.223077      5.56             0.042769   3.799462  1.304582   
1        0.074343     11.88             0.001197   9.884457  1.612960   
2        0.206128     17.81             0.049610   9.328440  3.078579   
3        0.054383      9.17             0.000922   7.584566  1.035998   
4        0.116826     53.59             0.021368  10.352085  5.564661   

    time_var  size_mean  size_std   size_var  cumlative_std  cumlative_mean  \
0   1.701934   3.799462  1.304582   1.701934   1.155035e+04   -1.223680e+04   
1   2.601640   9.884457  1.612960   2.601640   1.267953e+06   -2.078583e+06   
2   9.477649   9.328440  3.078579   9.477649   3.356314e+04   -4.929177e+04   
3   1.073292   7.584566  1.035998   1.073292   1.325829e+06   -2.252911e+06   
4  30.965449  10.352085  5.564661  30.965449   2.912004e+05   -4.890902e+05   

   cumlative_var     burst_std   burst_mean     burst_var  
0   1.334105e+08   3256.050568  -873.411765  1.060187e+07  
1   1.607704e+12   9848.794152 -5580.403101  9.699875e+07  
2   1.126484e+09   3692.740818 -1460.906667  1.363633e+07  
3   1.757823e+12  10112.978299 -6212.640219  1.022723e+08  
4   8.479766e+10   6851.747115 -2905.864307  4.694644e+07

In [51]:
import pandas as pd
import numpy as np

df_combined = pd.concat([df1, df2], axis=0, ignore_index=True)
df_combined.head()

label  packet_num  total_income  total_outcome  outgoing_ratio  \
0      1        1421           121           1300        0.914849   
1      1         518            80            438        0.845560   
2      1        1358           118           1240        0.913108   
3      1        1446           122           1324        0.915629   
4      1        1406           115           1291        0.918208   

   incoming_ratio  duration  duration_per_packet  time_mean  time_std  \
0        0.085151     10.14             0.007136   4.315749  1.128342   
1        0.154440     10.16             0.019614   4.611815  1.370610   
2        0.086892     11.11             0.008181   5.488969  1.179265   
3        0.084371     13.36             0.009239   5.995512  1.708888   
4        0.081792     10.64             0.007568   4.698869  1.297085   

   time_var  size_mean  size_std  size_var  cumlative_std  cumlative_mean  \
0  1.273156   4.315749  1.128342  1.273156  185143.121578  -307557.787474   
1  1.878571   4.611815  1.370610  1.878571   52114.349528   -86710.857143   
2  1.390665   5.488969  1.179265  1.390665  175190.919799  -297018.438881   
3  2.920298   5.995512  1.708888  2.920298  188050.453003  -316360.409405   
4  1.682428   4.698869  1.297085  1.682428  183907.494477  -308565.940256   

   cumlative_var    burst_std   burst_mean     burst_var  
0   3.427798e+10  7804.680303 -3901.109677  6.091303e+07  
1   2.715905e+09  5268.809112 -1981.935484  2.776035e+07  
2   3.069186e+10  7571.208934 -3811.178808  5.732320e+07  
3   3.536297e+10  7796.126033 -3873.811321  6.077958e+07  
4   3.382197e+10  7396.058816 -3838.369427  5.470169e+07

In [52]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

X = df_combined[['burst_mean','burst_std', 'burst_var','total_income', 'total_outcome', 'packet_num', 'outgoing_ratio', 'incoming_ratio', 'duration','time_mean', 'time_var','size_mean','size_std','size_var','cumlative_std','cumlative_mean','cumlative_var','duration_per_packet']]
y = df_combined['label']

# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Gradient Boosting 모델 생성 및 학습
model = GradientBoostingClassifier(learning_rate=0.01, n_estimators=100, random_state=42)
model.fit(X_train, y_train)

GradientBoostingClassifier(learning_rate=0.01, random_state=42)

In [53]:
from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score, confusion_matrix

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Accuracy를 퍼센트로 표시
accuracy_percent = accuracy * 100
print(f'Accuracy: {accuracy_percent:.2f}%')

# Precision
precision = precision_score(y_test, y_pred, average='micro')
print(f'Precision: {precision:.2f}')

# Recall
recall = recall_score(y_test, y_pred,average='macro' )
print(f'Recall: {recall:.2f}')


# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:\n', conf_matrix)

Accuracy: 67.86%
Precision: 0.68
Recall: 0.53
Confusion Matrix:
 [[ 157 1820]
 [  44 3779]]


##다중분류

In [ ]:
import pickle
with open("/content/drive/MyDrive/GitHub/global/mon2.pkl", 'rb') as fi: # Path to mon_standard.pkl in Colab
    df1 = pickle.load(fi)
print("Loading mon_df1_contiuous...")

import pickle
with open("/content/drive/MyDrive/GitHub/global/unmon2.pkl", 'rb') as fi: # Path to mon_standard.pkl in Colab
    df2 = pickle.load(fi)
print("Loading mon_df2_contiuous...")

Loading mon_df1_contiuous...
Loading mon_df2_contiuous...


In [ ]:
import pandas as pd
import numpy as np

df_combined = pd.concat([df1, df2], axis=0, ignore_index=True)
df_combined.head()

label  packet_num  total_income  total_outcome  outgoing_ratio  \
0      0        1421           121           1300        0.914849   
1      0         518            80            438        0.845560   
2      0        1358           118           1240        0.913108   
3      0        1446           122           1324        0.915629   
4      0        1406           115           1291        0.918208   

   incoming_ratio  duration  duration_per_packet  time_mean  time_std  \
0        0.085151     10.14             0.007136   4.315749  1.128342   
1        0.154440     10.16             0.019614   4.611815  1.370610   
2        0.086892     11.11             0.008181   5.488969  1.179265   
3        0.084371     13.36             0.009239   5.995512  1.708888   
4        0.081792     10.64             0.007568   4.698869  1.297085   

   time_var  size_mean  size_std  size_var  cumlative_std  cumlative_mean  \
0  1.273156   4.315749  1.128342  1.273156  185143.121578  -307557.787474   
1  1.878571   4.611815  1.370610  1.878571   52114.349528   -86710.857143   
2  1.390665   5.488969  1.179265  1.390665  175190.919799  -297018.438881   
3  2.920298   5.995512  1.708888  2.920298  188050.453003  -316360.409405   
4  1.682428   4.698869  1.297085  1.682428  183907.494477  -308565.940256   

   cumlative_var    burst_std   burst_mean     burst_var  
0   3.427798e+10  7804.680303 -3901.109677  6.091303e+07  
1   2.715905e+09  5268.809112 -1981.935484  2.776035e+07  
2   3.069186e+10  7571.208934 -3811.178808  5.732320e+07  
3   3.536297e+10  7796.126033 -3873.811321  6.077958e+07  
4   3.382197e+10  7396.058816 -3838.369427  5.470169e+07

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

X = df_combined[['burst_mean','burst_std', 'burst_var','total_income', 'total_outcome', 'packet_num', 'outgoing_ratio', 'incoming_ratio', 'duration','time_mean', 'time_var','size_mean','size_std','size_var','cumlative_std','cumlative_mean','cumlative_var','duration_per_packet']]
y = df_combined['label']

# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Gradient Boosting 모델 생성 및 학습
model = GradientBoostingClassifier(learning_rate=0.1, n_estimators=50, random_state=42)
model.fit(X_train, y_train)

GradientBoostingClassifier(n_estimators=50, random_state=42)

In [46]:
from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score, confusion_matrix

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Accuracy를 퍼센트로 표시
accuracy_percent = accuracy * 100
print(f'Accuracy: {accuracy_percent:.2f}%')

# Precision
precision = precision_score(y_test, y_pred, average='micro')
print(f'Precision: {precision:.2f}')

# Recall
recall = recall_score(y_test, y_pred,average='macro' )
print(f'Recall: {recall:.2f}')


# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:\n', conf_matrix)

Accuracy: 53.40%
Precision: 0.53
Recall: 0.40
Confusion Matrix:
 [[1604    5    4 ...   10    2    6]
 [  19    6    1 ...    0    0    0]
 [  11    1   15 ...    0    0    0]
 ...
 [  20    0    0 ...    8    0    0]
 [  16    0    0 ...    0   30    0]
 [  23    1    0 ...    1    0    6]]
